### ISSUE TITLE
door sense Error Unable to correct problems, you have held broken packages

### ISSUE THREAD

**Issue by ghazaliithnin** [robotics-ai/tof_process_public#6]
Greetings,

I was trying to install the sh file named install_door-sense_focal.sh, but at the end the error : Unable to correct problems, you have held broken packages prompted out.

Below is the log of command line i executed:

linaro@linaro-alip:~$ ls
1_install_glog_2021_07_28.txt
2_install_libwebsockets_2021_08_24.txt
3_protobuf_2021_08_25.txt
4_build_SDK_only_2021_08_25.txt
5_install_opencv_2021_08_25.txt
Desktop
Documents
Downloads
Music
Pictures
Public
Templates
Videos
aditof_sdk
glog
install_door-sense_dependencies_focal.sh
libwebsockets
protobuf
workspace
linaro@linaro-alip:~$ ./install_door-sense_dependencies_focal.shbash: ./install_door-sense_dependencies_focal.sh: Permission denied
linaro@linaro-alip:~$ chmod +x install_door-sense_dependencies_focal.sh
linaro@linaro-alip:~$ ./install_door-sense_dependencies_focal.shInstall dependencies
Executing: /tmp/apt-key-gpghome.2XNZ2isA4d/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/run/user/0/gnupg/d.simoyiprhprxh9d3sw7rh7u3/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
Ign:1 http://deb.debian.org/debian stretch InRelease           
Get:2 http://security.debian.org stretch/updates InRelease [53.0 kB]
Hit:3 http://deb.debian.org/debian stretch Release             
Get:6 http://packages.ros.org/ros/ubuntu focal InRelease [4676 B]
Ign:8 http://obs.linaro.org/qcom/stretch ./ InRelease          
Get:9 http://security.debian.org stretch/updates/main Sources [369 kB]
Ign:10 http://obs.linaro.org/linaro-overlay-stretch/Debian_9.0 ./ InRelease
Err:6 http://packages.ros.org/ros/ubuntu focal InRelease       
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
Hit:11 http://obs.linaro.org/qcom/stretch ./ Release           
Ign:4 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:13 http://obs.linaro.org/linaro-overlay-stretch/Debian_9.0 ./ Release
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:15 http://cdn-fastly.deb.debian.org/debian stretch Release 
Get:17 http://security.debian.org stretch/updates/main arm64 Packages [687 kB]
Reading package lists... Done                                  
W: GPG error: http://packages.ros.org/ros/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://packages.ros.org/ros/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-noetic-desktop-full
linaro@linaro-alip:~$ 

#######################################
##########################################

Since the  gpg: keyserver receive failed: No dirmngr prompted up, i decided to install the dirmngr using the command below:

#################################
sudo apt-get update -y
#################################

#####################################
install dirmngr
##################################

linaro@linaro-alip:~$ sudo apt-get install -y dirmngr
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  dbus-user-session tor
The following NEW packages will be installed:
  dirmngr
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 556 kB of archives.
After this operation, 1024 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main arm64 dirmngr arm64 2.1.18-8~deb9u4 [556 kB]
Fetched 556 kB in 1s (373 kB/s)
Selecting previously unselected package dirmngr.
(Reading database ... 112873 files and directories currently installed.)
Preparing to unpack .../dirmngr_2.1.18-8~deb9u4_arm64.deb ...
Unpacking dirmngr (2.1.18-8~deb9u4) ...
Setting up dirmngr (2.1.18-8~deb9u4) ...
linaro@linaro-alip:~$ 

#############################
#############################

My last attempt is to reinstall the sh file:

linaro@linaro-alip:~$ ./install_door-sense_dependencies_focal.shInstall dependencies
Executing: /tmp/apt-key-gpghome.SjuOLCx6FT/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
gpg: key F42ED6FBAB17C654: public key "Open Robotics <info@osrfoundation.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Get:1 http://security.debian.org stretch/updates InRelease [53.0 kB]
Ign:3 http://deb.debian.org/debian stretch InRelease           
Hit:4 http://deb.debian.org/debian stretch Release             
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:6 http://security.debian.org stretch/updates/main Sources [369 kB]
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Get:9 http://security.debian.org stretch/updates/main arm64 Packages [687 kB]
Ign:10 http://obs.linaro.org/qcom/stretch ./ InRelease         
Get:7 http://packages.ros.org/ros/ubuntu focal InRelease [4676 B]
Get:12 http://security.debian.org stretch/updates/main Translation-en [327 kB]
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch Release  
Ign:13 http://obs.linaro.org/linaro-overlay-stretch/Debian_9.0 ./ InRelease
Hit:14 http://obs.linaro.org/qcom/stretch ./ Release           
Hit:15 http://obs.linaro.org/linaro-overlay-stretch/Debian_9.0 ./ Release
Get:16 http://packages.ros.org/ros/ubuntu focal/main arm64 Packages [565 kB]
Fetched 2006 kB in 4s (464 kB/s)                             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/hwpack.repo.list:1 and /etc/apt/sources.list.d/linaro-overlay-obs.list:1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-noetic-desktop-full : Depends: ros-noetic-desktop but it is not going to be installed
                           Depends: ros-noetic-perception but it is not going to be installed
                           Depends: ros-noetic-simulators but it is not going to be installed
                           Depends: ros-noetic-urdf-sim-tutorial but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
linaro@linaro-alip:~$ 

################################################################

Thus the "Unable to correct problems, you have held broken packages." prompted up.

**Comment by stefansobol** [comment]
Hi,
Can you give us more details about your system?
copy paste the output of "uname -a"
Thanks

**Comment by ghazaliithnin** [comment]
> 
> 
> Hi,
> Can you give us more details about your system?
> copy paste the output of "uname -a"
> Thanks

This is the output from "uname -a"

Linux linaro-alip 4.9-camera-lt-qcom #1 SMP PREEMPT Tue Jan 19 08:38:27 EET 2021 aarch64 GNU/Linux

**Comment by stefansobol** [comment]
Your OS/Architecture is not supported. Here is our compatibility list:
- PC X64 Ubuntu 20.04 (focal)
- NVidia Xavier AGX/NX arm64 Ubuntu 18.04 (bionic)
Please check our [Readme](https://github.com/robotics-ai/tof_process_public/blob/main/door_sense/README.md) section "Hardware and software setup" file for more details

**Comment by ghazaliithnin** [comment]
> 
> 
> Your OS/Architecture is not supported. Here is our compatibility list:
> 
>     * PC X64 Ubuntu 20.04 (focal)
> 
>     * NVidia Xavier AGX/NX arm64 Ubuntu 18.04 (bionic)
>       Please check our [Readme](https://github.com/robotics-ai/tof_process_public/blob/main/door_sense/README.md) section "Hardware and software setup" file for more details

I see, thank you for your reply. I will inform the supplier on this matter.

**Comment by ghazaliithnin** [comment]
> 
> 
> Your OS/Architecture is not supported. Here is our compatibility list:
> 
>     * PC X64 Ubuntu 20.04 (focal)
> 
>     * NVidia Xavier AGX/NX arm64 Ubuntu 18.04 (bionic)
>       Please check our [Readme](https://github.com/robotics-ai/tof_process_public/blob/main/door_sense/README.md) section "Hardware and software setup" file for more details
 
The OS was build from DragonBoard 410c Platform. I downloaded and built the latest sd card image from https://github.com/stefansobol/aditof_sdk on Supported embedded platforms, 96-TOF1-EBZ, Platform DragonBoard 410c.


The board that I am using is **DragonBoard 410c DB410C-STD Rev B** attached together with **ADDI9035-36 REV B** and **08-051355 REV B, 96ToF LASER1**

Let me know if I missed out any other information that you required.

**Comment by stefansobol** [comment]
The DragonBoard is not one of our target platforms (at least not now). The SD card image from aditof_sdk for DragonBoard has the camera drivers and application to pass camera data to a USB interface, therefore to use the DragonBoard as middle man for camera data.
To run one of our applications we have one of the following options:
1) camera+dragonboard connected via USB to a PC X64 running Ubuntu 20.04
2) camera+NVidia Xavier AGX or NX running Ubuntu 18.04

Let me know if this helps

**Comment by ghazaliithnin** [comment]
> 
> 
> The DragonBoard is not one of our target platforms (at least not now). The SD card image from aditof_sdk for DragonBoard has the camera drivers and application to pass camera data to a USB interface, therefore to use the DragonBoard as middle man for camera data.
> To run one of our applications we have one of the following options:
> 
>     1. camera+dragonboard connected via USB to a PC X64 running Ubuntu 20.04
> 
>     2. camera+NVidia Xavier AGX or NX running Ubuntu 18.04
> 
> 
> Let me know if this helps

I understand that, thank you for the explanation. I will inform my supplier on this matter.
